### ISSUE TITLE
ibm_pi_volume_attach

### ISSUE THREAD

**Issue by powervs-ibm** [powervs-ibm/terraform-provider-ibm#57]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Documentation need to be updated to include detach. Since we do attach and detach.

<img width="738" alt="Screenshot 2024-02-09 at 3 35 09 PM" src="https://github.com/powervs-ibm/terraform-provider-ibm/assets/137309855/012eec22-e462-4796-993d-55aa23d4af1a">

### New or Affected Resource(s)

* resources  : ibm_pi_volume_attach

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by michaelkad** [comment]
This is correct, We have to create another resource to detach a volume.
